//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_7___Ejercicios.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public string IDventa { get; set; }
        public string Cod { get; set; }
        public decimal importe { get; set; }
        public System.DateTime fecha { get; set; }
        public int Cantidad { get; set; }
        public string vendedor { get; set; }
        public string cliente { get; set; }
    }
}
